-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgd/zmYNECrRtF+jOo+7kpIewF3BkBKcCXvy6gNIsw4ySgCgYIKoZIzj0DAQehRANCAAT8QCkKyU++YnK9xOET2TqxgDL4/rP30DOmN0YxIPF4biJ9yhmDWx68VLFkSQrjNl7FlH7Ik/y3PqqmJVdhIoVH
-----END PRIVATE KEY-----